#!/bin/sh

parse_opt()
{
    case "$1" in
        *\=*)
        local key_name="`echo "$1" | cut -f1 -d=`"
        local key_len=${#key_name}
        local value_start=$((key_len+2))
        echo "$1" | cut -c ${value_start}-
        ;;
    esac
}

for x in $(cat /proc/cmdline) ; do
    case "${x}" in
    ethx\=*)
        x=$(parse_opt ${x})
        NET_IFACE=$(echo ${x} | cut -d= -f1)
        NET_IPADDR=$(echo ${x} | cut -d= -f2)
        ;;
    gw\=*)
        x=$(parse_opt ${x})
        NET_GATEWAY=${x}
        ;;
    esac
done

if [[ -f /etc/hostname ]] ; then
    hostname $(< /etc/hostname)
else
    hostname rescue-$(uname -m)
fi

touch /etc/filesystems

[ -d /var/log ] || mkdir -p /var/log
dmesg > /var/log/dmesg

syslogd -O /var/log/messages -s 1024 -b 10 > /dev/null 2>&1

echo
echo ">>> Start sshd"
[ -d /dev/pts ] || mkdir /dev/pts
mount -t devpts devpts /dev/pts
for d in /etc/ssh /var/empty ; do
    [ -d "${d}" ] || mkdir -p ${d}
done
for k in rsa dsa ecdsa ed25519; do
    ssh-keygen -t ${k} -f /etc/ssh/ssh_host_${k}_key -N '' > /dev/null 2>&1
done
touch /etc/ssh/sshd_config
/usr/sbin/sshd -o "PermitRootLogin yes" -o "PermitEmptyPasswords yes"
echo

if [[ -d /sys/class/dmi/id ]]; then
    echo
    [ -s /sys/class/dmi/id/board_vendor ] && {
        echo -n " >> Board: "
        cat /sys/class/dmi/id/board_vendor
    }
    [ -s /sys/class/dmi/id/product_name ] && {
        echo -n " >> Product: "
        cat /sys/class/dmi/id/product_name
    }
    echo -n " >> Kernel: "
    uname -r
    echo
fi

ifconfig lo up

while [ 1 ] ; do
    echo " >> NIC found:" $(ls /sys/class/net)
    if [[ -n "${NET_IFACE}" && -n "${NET_IPADDR}" ]] ; then
        if [ ! -h /sys/class/net/${NET_IFACE} ] ; then
            echo " !! NIC \`${NET_IFACE}' not exist"
            break
        fi
        ip link set ${NET_IFACE} up
        echo " >>> set dev ${NET_IFACE} ip address to ${NET_IPADDR}"
        ip addr add dev ${NET_IFACE} ${NET_IPADDR} brd +
        if [ $? != 0 ] ; then
            break
        fi
        if [[ -n "${NET_GATEWAY}" ]] ; then
            echo " >>> set gateway to ${NET_GATEWAY}"
            ip route add default via ${NET_GATEWAY}
        fi
    fi
    break
done
